//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace propterHoc {


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class NetworkId {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class StateSaveData {

        private string stateNameField;

        private string stateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StateName
        {
            get { return this.stateNameField; }
            set { this.stateNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("State")]
        public string State
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Reagent {

        private string typeNameField;

        private string quantityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypeName
        {
            get { return this.typeNameField; }
            set { this.typeNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Quantity
        {
            get { return this.quantityField; }
            set { this.quantityField = value; }
        }
    }

    public class TransformerSaveData : MachineSaveData {
        private string outputSettingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OutputSetting
        {
            get { return this.outputSettingField; }
            set { this.outputSettingField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class WorldData {

        private string gameField;

        private string gameVersionField;

        private string dateTimeField;

        private string worldTypeField;

        private string worldSeedField;

        private string bedrockLevelField;

        private string sunTimeField;

        private string spawnPointsField;

        private string mothershipsField;

        private WorldDataRoomsRoom[] roomsField;

        private NetworkId[] pipeNetworksField;

        private NetworkId[] cableNetworksField;

        private NetworkId[] chuteNetworksField;

        private WorldDataThingsThingSaveData[] thingsField;

        private WorldDataAtmospheresAtmosphereSaveData[] atmospheresField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]

        public string Game
        {
            get { return this.gameField; }
            set { this.gameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameVersion
        {
            get { return this.gameVersionField; }
            set { this.gameVersionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateTime
        {
            get { return this.dateTimeField; }
            set { this.dateTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WorldType
        {
            get { return this.worldTypeField; }
            set { this.worldTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WorldSeed
        {
            get { return this.worldSeedField; }
            set { this.worldSeedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BedrockLevel
        {
            get { return this.bedrockLevelField; }
            set { this.bedrockLevelField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SunTime
        {
            get { return this.sunTimeField; }
            set { this.sunTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Room", typeof(WorldDataRoomsRoom),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public WorldDataRoomsRoom[] Rooms
        {
            get { return this.roomsField; }
            set { this.roomsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NetworkId", typeof(NetworkId))]
        public NetworkId[] PipeNetworks
        {
            get { return this.pipeNetworksField; }
            set { this.pipeNetworksField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NetworkId", typeof(NetworkId))]
        public NetworkId[] CableNetworks
        {
            get { return this.cableNetworksField; }
            set { this.cableNetworksField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NetworkId", typeof(NetworkId))]
        public NetworkId[] ChuteNetworks
        {
            get { return this.chuteNetworksField; }
            set { this.chuteNetworksField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SpawnPoints
        {
            get { return this.spawnPointsField; }
            set { this.spawnPointsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Motherships
        {
            get { return this.mothershipsField; }
            set { this.mothershipsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ThingSaveData", typeof(WorldDataThingsThingSaveData),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public WorldDataThingsThingSaveData[] Things
        {
            get { return this.thingsField; }
            set { this.thingsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AtmosphereSaveData",
            typeof(WorldDataAtmospheresAtmosphereSaveData), Form = System.Xml.Schema.XmlSchemaForm.Unqualified,
            IsNullable = false)]
        public WorldDataAtmospheresAtmosphereSaveData[] Atmospheres
        {
            get { return this.atmospheresField; }
            set { this.atmospheresField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataRoomsRoom {

        private string roomIdField;

        private string mothershipReferenceIdField;

        private WorldDataRoomsRoomGridsGrid[] gridsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Grid", typeof(WorldDataRoomsRoomGridsGrid),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public WorldDataRoomsRoomGridsGrid[] Grids
        {
            get { return this.gridsField; }
            set { this.gridsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RoomId
        {
            get { return this.roomIdField; }
            set { this.roomIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MothershipReferenceId
        {
            get { return this.mothershipReferenceIdField; }
            set { this.mothershipReferenceIdField = value; }
        }
        
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataRoomsRoomGridsGrid {

        private string xField;

        private string yField;

        private string zField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get { return this.xField; }
            set { this.xField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get { return this.yField; }
            set { this.yField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string z
        {
            get { return this.zField; }
            set { this.zField = value; }
        }
    }


    public class HumanSaveData : DynamicThingSaveData
    {
        private string stateField;

        private string genderIndexField;

        private string hairIndexField;

        private string facialhairIndexField;

        private string eyeIndexField;

        private string eyeColourIndexField;

        private string skinCololurIndexField;

        private string hairColourIndexField;

        private string skinIndexField;

        

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string State
        {
            get { return this.stateField; }
            set { this.stateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GenderIndex
        {
            get { return this.genderIndexField; }
            set { this.genderIndexField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HairIndex
        {
            get { return this.hairIndexField; }
            set { this.hairIndexField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FacialhairIndex
        {
            get { return this.facialhairIndexField; }
            set { this.facialhairIndexField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EyeIndex
        {
            get { return this.eyeIndexField; }
            set { this.eyeIndexField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EyeColourIndex
        {
            get { return this.eyeColourIndexField; }
            set { this.eyeColourIndexField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SkinCololurIndex
        {
            get { return this.skinCololurIndexField; }
            set { this.skinCololurIndexField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HairColourIndex
        {
            get { return this.hairColourIndexField; }
            set { this.hairColourIndexField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SkinIndex
        {
            get { return this.skinIndexField; }
            set { this.skinIndexField = value; }
        }

    }
    public class DynamicThingSaveData : WorldDataThingsThingSaveData
    {
        private string draggedField;

        private string draggedInteractionIndexField;

        private WorldDataThingsThingSaveDataVelocity[] velocityField;
        private WorldDataThingsThingSaveDataAngularVelocity[] angularVelocityField;
        private WorldDataThingsThingSaveDataDragOffset[] dragOffsetField;
        private string healthCurrentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dragged
        {
            get { return this.draggedField; }
            set { this.draggedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DraggedInteractionIndex
        {
            get { return this.draggedInteractionIndexField; }
            set { this.draggedInteractionIndexField = value; }
        }
        
        /// <remarks/>c
        [System.Xml.Serialization.XmlElementAttribute("DragOffset", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorldDataThingsThingSaveDataDragOffset[] DragOffset
        {
            get { return this.dragOffsetField; }
            set { this.dragOffsetField = value; }

        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Velocity", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorldDataThingsThingSaveDataVelocity[] Velocity
        {
            get { return this.velocityField; }
            set { this.velocityField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AngularVelocity", Form =
            System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorldDataThingsThingSaveDataAngularVelocity[] AngularVelocity
        {
            get { return this.angularVelocityField; }
            set { this.angularVelocityField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HealthCurrent
        {
            get { return this.healthCurrentField; }
            set { this.healthCurrentField = value; }
        }

    }
    public class CableSaveSaveData : StructureSaveData
    {
        private string cableNetworkIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CableNetworkId
        {
            get { return this.cableNetworkIdField; }
            set { this.cableNetworkIdField = value; }
        }

    }

    public class StackerSaveData : StructureSaveData {
        private string settingField;

        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Setting
        {
            get { return this.settingField; }
            set { this.settingField = value; }
        }
    }
    public class BatteryCellSaveData : DynamicThingSaveData
    {
        private string powerStoredField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PowerStored
        {
            get { return this.powerStoredField; }
            set { this.powerStoredField = value; }
        }
    }

    public class RoadflareSaveData : DynamicThingSaveData {
        private string lifetimeField;
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lifetime
        {
            get { return this.lifetimeField; }
            set { this.lifetimeField = value; }
        }
    }

    public class StackableSaveData : DynamicThingSaveData
    {
        private string quantityField;
        private string mothershipReferenceIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Quantity
        {
            get { return this.quantityField; }
            set { this.quantityField = value; }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MothershipReferenceId
        {
            get { return this.mothershipReferenceIdField; }
            set { this.mothershipReferenceIdField = value; }
        }
        
    }
    public class DeviceAtmosphericSaveData : StructureSaveData
    {
        private string outputSettingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OutputSetting
        {
            get { return this.outputSettingField; }
            set { this.outputSettingField = value; }
        }
    }
    public class CircuitboardSaveData : ElectronicSaveData
    {
        private string lastIndexField;

        private string filterStringField;


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastIndex
        {
            get { return this.lastIndexField; }
            set { this.lastIndexField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FilterString
        {
            get { return this.filterStringField; }
            set { this.filterStringField = value; }
        }
    }
    public class PipeSaveData : StructureSaveData
    {
        private string pipeNetworkIdField;

        private string isBurstField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PipeNetworkId
        {
            get { return this.pipeNetworkIdField; }
            set { this.pipeNetworkIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsBurst
        {
            get { return this.isBurstField; }
            set { this.isBurstField = value; }
        }
    }
    public class FertilizedEggSaveData : DynamicThingSaveData
    {
        private string eggHatchTimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EggHatchTime
        {
            get { return this.eggHatchTimeField; }
            set { this.eggHatchTimeField = value; }
        }
    }
    public class PlantSaveData : StackableSaveData
    {

        private string stageTimeField;

        private string stageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StageTime
        {
            get { return this.stageTimeField; }
            set { this.stageTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Stage
        {
            get { return this.stageField; }
            set { this.stageField = value; }
        }
    }
    public class ConsumableSaveData : DynamicThingSaveData {
        private string quantityField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Quantity
        {
            get { return this.quantityField; }
            set { this.quantityField = value; }
        }
    }
    public class DynamicGasCanisterSaveData : DynamicThingSaveData
    {
        private string outputSettingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OutputSetting
        {
            get { return this.outputSettingField; }
            set { this.outputSettingField = value; }
        }
    }
    public class BrainSaveData : DynamicThingSaveData
    {
        private string clientSteamIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClientSteamId
        {
            get { return this.clientSteamIdField; }
            set { this.clientSteamIdField = value; }
        }
    }
    public class GasMaskSaveData : DynamicThingSaveData
    {
        private string leakRatioField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LeakRatio
        {
            get { return this.leakRatioField; }
            set { this.leakRatioField = value; }
        }
    }
    public class SuitSaveData : GasMaskSaveData
    {
        private string outputSettingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OutputSetting
        {
            get { return this.outputSettingField; }
            set { this.outputSettingField = value; }
        }
    }
    public class StructureSaveData : WorldDataThingsThingSaveData
    {

        private string currentBuildStateField;
        private string mothershipReferenceIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrentBuildState
        {
            get { return this.currentBuildStateField; }
            set { this.currentBuildStateField = value; }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MothershipReferenceId
        {
            get { return this.mothershipReferenceIdField; }
            set { this.mothershipReferenceIdField = value; }
        }
    }
    public class SolarPanelSaveData : StructureSaveData
    {
       public enum ExposedData {
            Activate,
            SolarAngle
        }

        public enum ExposedAction {
            Power,
            Horizontal,
            Vertical
        }

        private string horizontalField;

        private string verticalField;

        private string targetHorizontalField;

        private string targetVerticalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Horizontal
        {
            get { return this.horizontalField; }
            set { this.horizontalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vertical
        {
            get { return this.verticalField; }
            set { this.verticalField = value; }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetHorizontal
        {
            get { return this.targetHorizontalField; }
            set { this.targetHorizontalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetVertical
        {
            get { return this.targetVerticalField; }
            set { this.targetVerticalField = value; }
        }
    }
    public class SolarControlSaveData : ElectronicSaveData
    {
        private string targetHorizontalField;

        private string targetVerticalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetHorizontal
        {
            get { return this.targetHorizontalField; }
            set { this.targetHorizontalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetVertical
        {
            get { return this.targetVerticalField; }
            set { this.targetVerticalField = value; }
        }
    }

    public class ElectronicSaveData : DynamicThingSaveData{
        private WorldDataThingsThingSaveDataLinkedDeviceReferences[] linkedDeviceReferencesField;

        private string flagField;

        private string masterMotherboardField;


        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LinkedDeviceReferences", Form =
            System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorldDataThingsThingSaveDataLinkedDeviceReferences[] LinkedDeviceReferences
        {
            get { return this.linkedDeviceReferencesField; }
            set { this.linkedDeviceReferencesField = value; }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Flag
        {
            get { return this.flagField; }
            set { this.flagField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MasterMotherboard
        {
            get { return this.masterMotherboardField; }
            set { this.masterMotherboardField = value; }
        }

    }
    public class LogicMotherboardSaveData : ElectronicSaveData
    {
        private WorldDataThingsThingSaveDataLogicStatesLogicState[] logicStatesField;

        private string currentLogicIndexField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LogicState",
            typeof(WorldDataThingsThingSaveDataLogicStatesLogicState),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public WorldDataThingsThingSaveDataLogicStatesLogicState[] LogicStates
        {
            get { return this.logicStatesField; }
            set { this.logicStatesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrentLogicIndex
        {
            get { return this.currentLogicIndexField; }
            set { this.currentLogicIndexField = value; }
        }
    }
    public class MultiMotherboardSaveData : ElectronicSaveData
    {
        private string currentTabField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrentTab
        {
            get { return this.currentTabField; }
            set { this.currentTabField = value; }
        }
    }
    public class ChuteSaveData : StructureSaveData
    {
        private string chuteNetworkIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChuteNetworkId
        {
            get { return this.chuteNetworkIdField; }
            set { this.chuteNetworkIdField = value; }
        }
    }
    public class SlagSaveData : StackableSaveData
    {
        private Reagent[] createdReagentsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Reagent", typeof(Reagent), IsNullable = false)]
        public Reagent[] CreatedReagents
        {
            get { return this.createdReagentsField; }
            set { this.createdReagentsField = value; }
        }
    }
    public class FurnaceSaveData : StructureSaveData
    {
        private string outputSettingField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OutputSetting
        {
            get { return this.outputSettingField; }
            set { this.outputSettingField = value; }
        }
    }
    public class FabricatorSaveData : StructureSaveData
    {
        private string jobsField;

        private string progressField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Jobs
        {
            get { return this.jobsField; }
            set { this.jobsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Progress
        {
            get { return this.progressField; }
            set { this.progressField = value; }
        }
    }
    public class BatterySaveData : MachineSaveData
    {
        private string powerStoredField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PowerStored
        {
            get { return this.powerStoredField; }
            set { this.powerStoredField = value; }
        }
    }
    public class MachineSaveData : StructureSaveData
    {
        private string machineStateField;

        private string goalPressureField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MachineState
        {
            get { return this.machineStateField; }
            set { this.machineStateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GoalPressure
        {
            get { return this.goalPressureField; }
            set { this.goalPressureField = value; }
        }
    }

    



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [XmlInclude(typeof(HumanSaveData))]
    [XmlInclude(typeof(DynamicThingSaveData))]
    [XmlInclude(typeof(CableSaveSaveData))]
    [XmlInclude(typeof(BatteryCellSaveData))]
    [XmlInclude(typeof(StackableSaveData))]
    [XmlInclude(typeof(DeviceAtmosphericSaveData))]
    [XmlInclude(typeof(CircuitboardSaveData))]
    [XmlInclude(typeof(PipeSaveData))]
    [XmlInclude(typeof(FertilizedEggSaveData))]
    [XmlInclude(typeof(PlantSaveData))]
    [XmlInclude(typeof(ConsumableSaveData))]
    [XmlInclude(typeof(DynamicGasCanisterSaveData))]
    [XmlInclude(typeof(BrainSaveData))]
    [XmlInclude(typeof(GasMaskSaveData))]
    [XmlInclude(typeof(SuitSaveData))]
    [XmlInclude(typeof(StructureSaveData))]
    [XmlInclude(typeof(SolarPanelSaveData))]
    [XmlInclude(typeof(SolarControlSaveData))]
    [XmlInclude(typeof(LogicMotherboardSaveData))]
    [XmlInclude(typeof(MultiMotherboardSaveData))]
    [XmlInclude(typeof(ChuteSaveData))]
    [XmlInclude(typeof(SlagSaveData))]
    [XmlInclude(typeof(FurnaceSaveData))]
    [XmlInclude(typeof(FabricatorSaveData))]
    [XmlInclude(typeof(BatterySaveData))]
    [XmlInclude(typeof(MachineSaveData))]
    [XmlInclude(typeof(TransformerSaveData))]
    [XmlInclude(typeof(StackerSaveData))]
    [XmlInclude(typeof(RoadflareSaveData))]
    public partial class WorldDataThingsThingSaveData {

        private string referenceIdField;

        private string prefabNameField;

        private string customNameField;

        private string isCustomNameField;

        private string customColorIndexField;

        private string ownerSteamIdField;

        private string indestructableField;

        

        

        

        private string parentReferenceIdField;

        private string parentSlotIdField;



















        

        

       


        private WorldDataThingsThingSaveDataWorldPosition[] worldPositionField;

        private WorldDataThingsThingSaveDataWorldRotation[] worldRotationField;

        private StateSaveData[] statesField;

        private Reagent[] reagentsField;

        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferenceId
        {
            get { return this.referenceIdField; }
            set { this.referenceIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrefabName
        {
            get { return this.prefabNameField; }
            set { this.prefabNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomName
        {
            get { return this.customNameField; }
            set { this.customNameField = value; }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorldPosition", Form =
            System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorldDataThingsThingSaveDataWorldPosition[] WorldPosition
        {
            get { return this.worldPositionField; }
            set { this.worldPositionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorldRotation", Form =
            System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorldDataThingsThingSaveDataWorldRotation[] WorldRotation
        {
            get { return this.worldRotationField; }
            set { this.worldRotationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("State", typeof(StateSaveData), IsNullable = false)]
        public StateSaveData[] States
        {
            get { return this.statesField; }
            set { this.statesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsCustomName
        {
            get { return this.isCustomNameField; }
            set { this.isCustomNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomColorIndex
        {
            get { return this.customColorIndexField; }
            set { this.customColorIndexField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OwnerSteamId
        {
            get { return this.ownerSteamIdField; }
            set { this.ownerSteamIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Reagent", typeof(Reagent), IsNullable = false)]
        public Reagent[] Reagents
        {
            get { return this.reagentsField; }
            set { this.reagentsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Indestructable
        {
            get { return this.indestructableField; }
            set { this.indestructableField = value; }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParentReferenceId
        {
            get { return this.parentReferenceIdField; }
            set { this.parentReferenceIdField = value; }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParentSlotId
        {
            get { return this.parentSlotIdField; }
            set { this.parentSlotIdField = value; }
        }


    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataThingsThingSaveDataWorldPosition {

        private string xField;

        private string yField;

        private string zField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get { return this.xField; }
            set { this.xField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get { return this.yField; }
            set { this.yField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string z
        {
            get { return this.zField; }
            set { this.zField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataThingsThingSaveDataWorldRotation {

        private string xField;

        private string yField;

        private string zField;

        private string wField;

        private WorldDataThingsThingSaveDataWorldRotationEulerAngles[] eulerAnglesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get { return this.xField; }
            set { this.xField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get { return this.yField; }
            set { this.yField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string z
        {
            get { return this.zField; }
            set { this.zField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string w
        {
            get { return this.wField; }
            set { this.wField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eulerAngles", Form =
            System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorldDataThingsThingSaveDataWorldRotationEulerAngles[] eulerAngles
        {
            get { return this.eulerAnglesField; }
            set { this.eulerAnglesField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataThingsThingSaveDataWorldRotationEulerAngles {

        private string xField;

        private string yField;

        private string zField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get { return this.xField; }
            set { this.xField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get { return this.yField; }
            set { this.yField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string z
        {
            get { return this.zField; }
            set { this.zField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataThingsThingSaveDataDragOffset {

        private string xField;

        private string yField;

        private string zField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get { return this.xField; }
            set { this.xField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get { return this.yField; }
            set { this.yField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string z
        {
            get { return this.zField; }
            set { this.zField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataThingsThingSaveDataVelocity {

        private string xField;

        private string yField;

        private string zField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get { return this.xField; }
            set { this.xField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get { return this.yField; }
            set { this.yField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string z
        {
            get { return this.zField; }
            set { this.zField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataThingsThingSaveDataAngularVelocity {

        private string xField;

        private string yField;

        private string zField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get { return this.xField; }
            set { this.xField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get { return this.yField; }
            set { this.yField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string z
        {
            get { return this.zField; }
            set { this.zField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataThingsThingSaveDataLinkedDeviceReferences {

        private string longField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @long
        {
            get { return this.longField; }
            set { this.longField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataThingsThingSaveDataLogicStatesLogicState {

        private string displayNameField;

        private string isTriggeredField;

        private string nextLogicIndexField;

        private WorldDataThingsThingSaveDataLogicStatesLogicStateConditionsCondition[] conditionsField;

        private WorldDataThingsThingSaveDataLogicStatesLogicStateActionsAction[] actionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DisplayName
        {
            get { return this.displayNameField; }
            set { this.displayNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Condition",
            typeof(WorldDataThingsThingSaveDataLogicStatesLogicStateConditionsCondition),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public WorldDataThingsThingSaveDataLogicStatesLogicStateConditionsCondition[] Conditions
        {
            get { return this.conditionsField; }
            set { this.conditionsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Action",
            typeof(WorldDataThingsThingSaveDataLogicStatesLogicStateActionsAction),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public WorldDataThingsThingSaveDataLogicStatesLogicStateActionsAction[] Actions
        {
            get { return this.actionsField; }
            set { this.actionsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsTriggered
        {
            get { return this.isTriggeredField; }
            set { this.isTriggeredField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NextLogicIndex
        {
            get { return this.nextLogicIndexField; }
            set { this.nextLogicIndexField = value; }
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataThingsThingSaveDataLogicStatesLogicStateConditionsCondition {

        private string deviceReferenceIdField;

        private string typeField;

        private string operationField;

        private string valueField;

        private string isDisconnectedField;

        private string isTrueField;

       public enum NumericOperation {
            Equal,
            Less,
            Greater
        }

        public enum BooleanOperation {
            NOT,
            IS
        }

        public enum BooleanState {
            OFF,
            ON,
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeviceReferenceId
        {
            get { return this.deviceReferenceIdField; }
            set { this.deviceReferenceIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Operation
        {
            get { return this.operationField; }
            set { this.operationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsDisconnected
        {
            get { return this.isDisconnectedField; }
            set { this.isDisconnectedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsTrue
        {
            get { return this.isTrueField; }
            set { this.isTrueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataThingsThingSaveDataLogicStatesLogicStateActionsAction {

        private string deviceReferenceIdField;

        private string typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeviceReferenceId
        {
            get { return this.deviceReferenceIdField; }
            set { this.deviceReferenceIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type
        {
            get { return this.typeField; }
            set { this.typeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataAtmospheresAtmosphereSaveData {

        private string oxygenField;

        private string nitrogenField;

        private string carbonDioxideField;

        private string volatilesField;

        private string chlorineField;

        private string waterField;

        private string energyField;

        private string volumeField;

        private string networkReferenceIdField;

        private string thingReferenceIdField;

        private string cleanBurnRateField;

        private string mothershipReferenceIdField;

        private WorldDataAtmospheresAtmosphereSaveDataPosition[] positionField;

        private WorldDataAtmospheresAtmosphereSaveDataDirection[] directionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Position", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorldDataAtmospheresAtmosphereSaveDataPosition[] Position
        {
            get { return this.positionField; }
            set { this.positionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Oxygen
        {
            get { return this.oxygenField; }
            set { this.oxygenField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nitrogen
        {
            get { return this.nitrogenField; }
            set { this.nitrogenField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CarbonDioxide
        {
            get { return this.carbonDioxideField; }
            set { this.carbonDioxideField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Volatiles
        {
            get { return this.volatilesField; }
            set { this.volatilesField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Chlorine
        {
            get { return this.chlorineField; }
            set { this.chlorineField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Water
        {
            get { return this.waterField; }
            set { this.waterField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Energy
        {
            get { return this.energyField; }
            set { this.energyField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Volume
        {
            get { return this.volumeField; }
            set { this.volumeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Direction", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WorldDataAtmospheresAtmosphereSaveDataDirection[] Direction
        {
            get { return this.directionField; }
            set { this.directionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NetworkReferenceId
        {
            get { return this.networkReferenceIdField; }
            set { this.networkReferenceIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ThingReferenceId
        {
            get { return this.thingReferenceIdField; }
            set { this.thingReferenceIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CleanBurnRate
        {
            get { return this.cleanBurnRateField; }
            set { this.cleanBurnRateField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MothershipReferenceId
        {
            get { return this.mothershipReferenceIdField; }
            set { this.mothershipReferenceIdField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataAtmospheresAtmosphereSaveDataPosition {

        private string xField;

        private string yField;

        private string zField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get { return this.xField; }
            set { this.xField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get { return this.yField; }
            set { this.yField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string z
        {
            get { return this.zField; }
            set { this.zField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WorldDataAtmospheresAtmosphereSaveDataDirection {

        private string xField;

        private string yField;

        private string zField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x
        {
            get { return this.xField; }
            set { this.xField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y
        {
            get { return this.yField; }
            set { this.yField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string z
        {
            get { return this.zField; }
            set { this.zField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NetworkId", typeof(NetworkId), IsNullable = true)]
        [System.Xml.Serialization.XmlElementAttribute("Reagent", typeof(Reagent))]
        [System.Xml.Serialization.XmlElementAttribute("State", typeof(StateSaveData))]
        [System.Xml.Serialization.XmlElementAttribute("WorldData", typeof(WorldData))]
        public object[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }
    }
}